proyecto/cms/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
    path('loggedIn', views.loggedIn),
    path('logout', views.logout_view),
    path('login', views.iniciar_sesion),
    path('<str:llave>', views.get_content),
]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView as login

urlpatterns = [
    path('cms/', include('cms.urls')),
    path('admin/', admin.site.urls),
    path('login', login.as_view()),
]

proyecto/cms/models.py
from django.db import models

# Create your models here.

class Contenido(models.Model):
    clave = models.CharField(max_length=64)
    valor = models.TextField()

class Comentario(models.Model):
    contenido = models.ForeignKey(Contenido, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    cuerpo = models.TextField(blank=False)
    fecha = models.DateTimeField('publicado')

proyecto/cms/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.template import loader
from django.contrib.auth import logout

from .models import Contenido, Comentario


# Create your views here.


@csrf_exempt
def get_content(request, llave):
    if request.method == "PUT":
        valor = request.body.decode('utf-8')
    elif request.method == "POST":
        action = request.POST['action']
        if action == "Enviar Contenido":
            valor = request.POST['valor']
    if request.method == "PUT" or (request.method == "POST" and action == "Enviar Contenido"):
        try:
            c = Contenido.objects.get(clave=llave)
            c.valor = valor
        except Contenido.DoesNotExist:
            c = Contenido(clave=llave, valor=valor)
        c.save()
    if request.method == "POST" and action == "Enviar Comentario":
            c = get_object_or_404(Contenido, clave=llave)
            titulo = request.POST['titulo']
            cuerpo = request.POST['cuerpo']
            q = Comentario(contenido=c, titulo=titulo, cuerpo=cuerpo, fecha=timezone.now())
            q.save()

    contenido = get_object_or_404(Contenido, clave=llave)
    autenticado = request.user.is_authenticated
    usuario = request.user.username
    context = {'contenido': contenido, 'autenticado':autenticado, 'user': usuario}
    return render(request, 'cms/content.html', context)


def index(request):
    content_list = Contenido.objects.all()[:5]
    autenticado = request.user.is_authenticated
    context = {'content_list': content_list, 'autenticado':autenticado}
    return render(request, 'cms/index.html', context)


def loggedIn(request):
    if request.user.is_authenticated:
        logged = "Logged in as " + request.user.username
    else:
        logged = "Not logged in. <a href='/admin/'>Login via admin</a>"
    return HttpResponse(logged)


def logout_view(request):
    logout(request)
    return redirect("/cms/")


def iniciar_sesion(request):
    return redirect("/login")

proyecto/cms/templates/cms/content.html
{% if autenticado %}
    <p>Logged in as {{ user }} <a href="logout">Logout</a></p>
    <hr>
{% else %}
    <p>Not logged in. <a href="login">Login</a></p>
    <hr>
{% endif %}

<h1>{{ contenido.valor }}</h1>
{% for comentario in contenido.comentario_set.all %}
    <hr>
    <h1>{{ comentario.titulo }}</h1><br>
        {{ comentario.cuerpo }}<br>
        Enviado el {{ comentario.fecha }}<br>
{% endfor %}


{% if autenticado %}
    <hr>
    <br>
    <form action="" method="POST">
      Introduce el (nuevo) contenido para esta página:
      <input type="text" name="valor">
      <input type="submit" name="action" value="Enviar Contenido">
    </form>

    <br>
    <form action="" method="POST">
      Introduce un nuevo comentario para esta página:
      <br>Título: <input type="text" name="titulo">
      <br>Cuerpo: <input type="text" name="cuerpo">
      <input type="submit" name="action" value="Enviar Comentario">
    </form>
{% endif %}

proyecto/cms/templates/cms/index.html
{% if autenticado %}
    <p>Logged in as {{ user }} <a href="logout">Logout</a></p>
    <hr>
{% else %}
    <p>Not logged in. <a href="login">Login</a></p>
    <hr>
{% endif %}

{% if content_list %}
    <ul>
    {% for content in content_list %}
        <li><a href="{{ content.clave }}">{{ content.clave }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No contents are available.</p>
{% endif %}